# Check for licenses and advisores
# ../../deny.toml
name: Cargo deny

on:
  workflow_call:
    inputs:
      bump-version:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      bump-version:
        description: "Bump version: (e.g. -> 3.6.1)"
        required: true
        type: string

jobs:
  cargo-semver-checks:
    runs-on: ubuntu-latest
    steps: 
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-bump
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-bump

      - name: Run cargo bump
        run: cargo bump ${{ inputs.bump-version }}
      
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          rust-toolchain: manual
          shared-key: my-workspace-semver