name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: cargo-build
        run: cargo build
          
      - name: cargo-clippy
        run: cargo clippy -- -D warnings

      - name: cargo-fmt
        run: cargo fmt --all -- --check

