name: CI

on:
  # workflow_dispatch:
  push:
    branches:
      - main
      # workflow_call:
        # pull_request:  
    
jobs:
  cargo-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: cargo build
        run: cargo b

  cargo-fmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  cargo-clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          components: clippy

      - name: Clippy Check
        run: cargo clippy

  typos-cli:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Typos 
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli

      - name: run typos
        run: typos

  taplo-toml-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - name: Run Taplo
        id: taplo
        run: taplo fmt --check --diff