name: Monthly Releases

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true   

permissions:
  contents: write

jobs:
  build_and_release:
    uses: ./.github/workflows/build_and_release.yaml
    with: 
      release_type: patch
      check-to-publish: true
    
