name: Publish

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Git Pull
        run: git pull

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cargo Publish
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
