name: Publish

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v4

    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - uses: katyo/publish-crates@v2
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true