name: build

permissions:
  # To upload files to GitHub Releases
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:
    inputs:
      version:
        description: "Add tag version: (e.g. -> v3.6.1)"
        required: true

jobs:
  create-tag:
    if: ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ inputs.version }}

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: aarch64-apple-darwin, os: macos-latest }
          - { target: aarch64-pc-windows-msvc, os: windows-latest }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ github.event.repository.name }}
          target: ${{ matrix.job.target }}
          include: attribution
          token: ${{ secrets.GITHUB_TOKEN }}
