name: Build & Release

permissions:
  # To upload files to GitHub Releases
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:
    inputs:
      version:
        description: "Add tag version: (e.g. -> v3.6.1)"
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: ${{ inputs.version }}
      - name: Create tag
        uses: actions/github-script@v5
        if: steps.check-tag.outputs.exists == 'false'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ inputs.version }}',
                sha: context.sha
              })

  create-release:
    needs: [create-tag]
    runs-on: ubuntu-latest
    steps:
      - id: get-tag
        uses: olegtarasov/get-tag@v2.1.2
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ inputs.version ||  github.ref_name }}

  build-and-release:
    needs: [create-release]
    name: ${{ matrix.target }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest 
          - target: x86_64-pc-windows-msvc
            os: windows-latest 
          - target: aarch64-unknown-linux-gnu 
            os: ubuntu-latest 
          - target: aarch64-apple-darwin, od
            os: macos-latest 
          - target: aarch64-pc-windows-msvc
            os: windows-latest 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ github.event.repository.name }}
          target: ${{ matrix.target }}
          include: attribution
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ inputs.version ||  github.ref_name }}
