name: Weekly Checks

on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true   

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yaml