[self]
name = "cargo-attribution"
version = "0.8.7"
description = "A cargo subcommand to give credit to your dependencies"
license = "MPL-2.0"
authors = ["AmeKnite"]
repository = "https://github.com/ameknite/cargo-attribution"
